### ISSUE TITLE
Add Python 3 support

### ISSUE THREAD

**Issue by jni** [CellProfiler/python-bioformats#12]
I have no idea how hard this is, but I'm in the "Python 3" birds-of-a-feather session at SciPy 2014 and realised this is one of the only libraries I use that is not Python 3 compatible.

(or, at the very least, "pip install python-bioformats" works for me in 2 envs but not 3.)

**Comment by sebi06** [comment]
Are there any News on the Python 3 Support yet?

**Comment by LeeKamentsky** [comment]
Hi all, unfortunately, it's not enough of a priority for us yet that we can justify spending the time. The blocker is https://github.com/CellProfiler/python-javabridge/issues/54. Other than that, I imagine it's pretty straightforward. And if anyone has the time to do the work, I would appreciate a pull request.

**Comment by sdh4** [comment]
I think my patch attached to CellProfiler/python-javabridge#54  pretty much covers things for javabridge.  I tested that out and it works no problem.

**Comment by LeeKamentsky** [comment]
Thx @sdh4. Do you have time to submit a pull request? If 3.x was added here: "https://github.com/CellProfiler/python-javabridge/blob/master/.travis.yml#L3" and Travis passed with your changes, I would be very grateful.

**Comment by kraftlj** [comment]
What's the status on this project? Is there a list of things to do?

**Comment by LeeKamentsky** [comment]
It's being actively used by CellProfiler (http://cellprofiler.org). We are currently running CellProfiler on Python 2.7 and officially, there's no funding for any Python 3.5 development, but we do try to support the community informally.

There's no "to do" list currently - we're pretty satisfied with how Bio-Formats works at the moment.

**Comment by kraftlj** [comment]
I meant with the python 3.5 development. Are there things that still need to be done where I can contribute?

**Comment by LeeKamentsky** [comment]
It would be great if you could contribute a patch for changes necessary to work on 3.5. If you fork the repository and work on a branch, you can submit a pull request which we would gladly take.

The standard approach is to run [2to3](https://docs.python.org/2/library/2to3.html) on the source files which somewhat automates the conversion process, then do whatever fixups are necessary. I think the main problems will be handling unicode file names and metadata.
