### ISSUE TITLE
Updating loci_tools.jar

### ISSUE THREAD

**Issue by caspervdw** [CellProfiler/python-bioformats#19]
Hi all,

For my nikon nd2 files, I need a newer loci_tools.jar. The version distributed with python-bioformats  gives me a division by zero (java) exception, while the newest version 5.0.6 works fine. I guess more users will have this problem, especially when setting up python-bioformats.

I wonder if there is a reason against updating the JAR file on a regular basis? And if there is any way to do this dynamically?

I get my loci_tools.jar from here:
http://downloads.openmicroscopy.org/bio-formats/5.0.6/#components

**Comment by LeeKamentsky** [comment]
I can update it when I get back from the New Year closing, I guess, the way I use it, both informally and in CellProfiler, I usually start the Javabridge with a Jar other than the default. Partly it's the devil you know versus the one you don't; there's always a chance that the unit tests won't catch some subtle incompatibility when we switch. There are many ways we could support configurable versions, from using Maven to maintaining an archive of them at CellProfiler.org, but for now, maybe the simple path of manually updating the version, within the code base is the safest.

**Comment by caspervdw** [comment]
For https://github.com/soft-matter/pims , I am working on a wrapper for python-bioformats. For testing, I am configuring Travis to install javabridge and python-bioformats, and now manually updating the jar becomes more difficult. I could also put in another jar in pims and use that one, but that would make pims a lot heavier. 

So if it doesn't raise any problems, I would appriciate an update of the jar in python-bioformats ;)
