### ISSUE TITLE
Python BioFormats does not work any more

### ISSUE THREAD

**Issue by sebi06** [CellProfiler/python-bioformats#22]
Hi guys,

since today I have a seroius problem on my Windows7 64bit machine. I use javabrige 1.0.9, bioformats 1.0.4 and bioformats_package 5.0.8. Until Friday this worked fine but since today I get:

Python 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import javabridge as jv
>>> import bioformats
>>> path = r'C:\Users\M1SRH\Documents\Software\Bio-Formats_Package\5.0.8\bioformats_package.jar'
>>> jars = jv.JARS + [path]
>>> jv.start_vm(class_path=jars, max_heap_size='2G')
>>> imagefile = r'C:\Users\M1SRH\Documents\Spyder_Projects_Testdata\CZI_Read\XYZCT_Z=15_C=2_T=20.czi'
>>> rdr = bioformats.get_image_reader(None, path=imagefile)
Failed to get class loci/common/RandomAccessInputStream
java.lang.NoClassDefFoundError: loci/common/RandomAccessInputStream
Caused by: java.lang.ClassNotFoundException: loci.common.RandomAccessInputStream
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\bioformats\formatreader.py", line 900, in get_image_reader
    rdr = ImageReader(path=path, url=url)
  File "C:\Python27\lib\site-packages\bioformats\formatreader.py", line 621, in __init__
    self.path)
  File "C:\Python27\lib\site-packages\javabridge\jutil.py", line 1655, in make_instance
    raise JavaException(jexception)
javabridge.jutil.JavaException: loci/common/RandomAccessInputStream
>>> 

The sample dataset used can be downloaded here:

https://www.dropbox.com/s/fu4ijim5a4n8tka/XYZCT_Z%3D15_C%3D2_T%3D20.czi?dl=0

I hope you can find the problem soon ... Let me know, if you need more infor or help.

Sebi

**Comment by sebi06** [comment]
I tested the same code on my ubuntu 14.10 using the same image data set and it works fine ...

Any idea, what the problem on my Windows 7 system could be?

**Comment by sebi06** [comment]
I did not wnat to close this. That was by accident ... sorry. Sebi

**Comment by LeeKamentsky** [comment]
Sorry about the late reply - I'm overseas. I would try replacing the backslashes in your path to the jar file with forward ones. I recall having a similar problem and that was the solution.

**Comment by sebi06** [comment]
Hi Lee, I tried, but this did not help:

import javabridge as jv
import bioformats
path = r'C:/Users/M1SRH/Documents/Software/Bio-Formats_Package/5.0.8/bioformats_package.jar'
jars = jv.JARS + [path]
jv.start_vm(class_path=jars, max_heap_size='2G')
imagefile = r'C:/Users/M1SRH/Documents/Spyder_Projects_Testdata/CZI_Read/XYZCT_Z=15_C=2_T=20.czi'
rdr = bioformats.get_image_reader(None, path=imagefile)

Failed to get class loci/common/RandomAccessInputStream
Traceback (most recent call last):

  File "<ipython-input-10-bf513e85b7f0>", line 1, in <module>
    rdr = bioformats.get_image_reader(None, path=imagefile)

  File "C:\Python27\lib\site-packages\python_bioformats-1.0.4-py2.7.egg\bioformats\formatreader.py", line 900, in get_image_reader
    rdr = ImageReader(path=path, url=url)

  File "C:\Python27\lib\site-packages\python_bioformats-1.0.4-py2.7.egg\bioformats\formatreader.py", line 621, in __init__
    self.path)

  File "C:\Python27\lib\site-packages\javabridge-1.0.9-py2.7-win-amd64.egg\javabridge\jutil.py", line 1655, in make_instance
    raise JavaException(jexception)

JavaException: loci/common/RandomAccessInputStream

java.lang.NoClassDefFoundError: loci/common/RandomAccessInputStream
Caused by: java.lang.ClassNotFoundException: loci.common.RandomAccessInputStream
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
java.lang.NoClassDefFoundError: loci/common/RandomAccessInputStream
Caused by: java.lang.ClassNotFoundException: loci.common.RandomAccessInputStream
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by LeeKamentsky** [comment]
I looked inside a copy of bioformats_package.jar that I have - the
RandomAccessInputStream class isn't there. I think that you may need some
other jar to get it. I'm away at a workshop this week, so I have limited
time to look into this unfortunately. I can do more next week. You might
need some scifio jar as well. You might try posting on the bioformats
mailing list for help.

**Comment by joshmoore** [comment]
Hi all. Can someone give me the a checksum for that file and/or where it came from? Looking at the reference jar (from the downloads page):
```
/ome/www/downloads.openmicroscopy.org/bio-formats/5.0.8/artifacts $ jar tvf bioformats_package.jar | grep RandomAccessInputStream
 11251 Sat Feb 07 10:00:26 GMT 2015 loci/common/RandomAccessInputStream.class

/ome/www/downloads.openmicroscopy.org/bio-formats/5.0.8/artifacts $ md5sum bioformats_package.jar
c481f768126aa6a71b380918c34970e8  bioformats_package.jar
/ome/www/downloads.openmicroscopy.org/bio-formats/5.0.8/artifacts $ cat bioformats_package.jar.md5
c481f768126aa6a71b380918c34970e8  bioformats_package.jar
```

**Comment by LeeKamentsky** [comment]
$ md5sum /c/Users/leek/Downloads/bioformats_package.jar
870ba4d84e2e339d28d3cc0d3030b73b */c/Users/leek/Downloads/bioformats_package.jar

That's the one I reported on this morning.

**Comment by joshmoore** [comment]
Hmmm.... the [artifactory file](http://artifacts.openmicroscopy.org/artifactory/simple/ome.releases/ome/bioformats_package/5.0.8/) has the md5: c3e1422364d986bf90a44eec164da15f

Not sure where this file came from

**Comment by LeeKamentsky** [comment]
Not sure if I can check much on my end this week, Josh. I'd download that one but the internet's a bit spotty here - will get back home next week and can look at it then and figure out what happened to that class. Thanks for checking.

**Comment by sebi06** [comment]
Hi guys,
just a side note.

I works fine on my Ubuntu with bioformats_package.jar I use there. When I transfer the same .jar to my Windows7 machine, I get the problem described above.
It all worked fine (as far as I remeber) with all previous versions of the bioformats_package.jar on all systems. Unfortunately I cannot Linux at work, because the ZEN sofwtare only runs on windows of course ... 

And should I post this really on the BioFormats mailing list ordid you do this already?

**Comment by sebi06** [comment]
And on more thing, what puzzles me. 

Even I replace the 5.0.8 version with older ones that used to work for sure on my windows, I always get the same problem...? Doesn't this mean, that the problem lies somewhere else and not within the bioformats_package.jar itself?

**Comment by sebi06** [comment]
Are there any news on this problem. I also testet this at a different machine wirg Windows8. It worked without any problems, so I am really confused why it is not working on my system.

Sebi

**Comment by LeeKamentsky** [comment]
I tried it myself with 5.0.8 (http://artifacts.openmicroscopy.org/artifactory/simple/ome.releases/ome/bioformats_package/5.0.8/bioformats_package-5.0.8.jar) - it works fine. How about printing out the class path after starting the javabridge:

import os
paths = jv.JClassWrapper('java.lang.System').getProperty('java.class.path').split(";")
for path in paths:
    print "%s: %s" %("exists" if os.path.isfile(path) else "missing", path)

**Comment by sebi06** [comment]
Hi Lee,

ok, I ran this file:

import os
import javabridge as jv
path = r'C:\Users\M1SRH\Documents\Software\Bio-Formats_Package\5.0.8\bioformats_package.jar'
jars = jv.JARS + [path]
jv.start_vm(class_path=jars, max_heap_size='2G')
paths = jv.JClassWrapper('java.lang.System').getProperty('java.class.path').split(";")
for path in paths:
    print "%s: %s" %("exists" if os.path.isfile(path) else "missing", path)


and I got:

exists: C:\Python27\lib\site-packages\javabridge-1.0.9-py2.7-win-amd64.egg\javabridge\jars\rhino-1.7R4.jar
exists: C:\Python27\lib\site-packages\javabridge-1.0.9-py2.7-win-amd64.egg\javabridge\jars\runnablequeue.jar
missing: C:/Users/M1SRH/Documents/Software/Bio-Formats_Package/5.0.8/bioformats_package.jar

**Comment by sebi06** [comment]
Does this mean somebody or something removed my bioformats_package.jar from my path and I just have to add it to make it work?

**Comment by LeeKamentsky** [comment]
I'm not able to tell you why there's no file, "C:/Users/M1SRH/Documents/Software/Bio-Formats_Package/5.0.8/bioformats_package.jar", just that it's not there. If you correct the path or move the file, it should work.

**Comment by sebi06** [comment]
Hi Lee,

I must Admit that I look a bit like an idiot now ... :-) But I all boilded down to some backup problems, which lead to a remamed folder ... That was it and was to blind to notice ...
Sorry for the trouble and thnaks for the help.

Sebi
