### ISSUE TITLE
Accessing Metadata and chnage in API

### ISSUE THREAD

**Issue by sebi06** [CellProfiler/python-bioformats#24]
Hi,

I am using the BioFormats package 5.1.1 from python (via python-bioformats) and noticed, that my old code does not work any more.

To get the scaling I used before (throws an error):

getPixelsPhysicalSizeX(0).getValue().floatValue()

but this seems to be now:

getPixelsPhysicalSizeX(0).value().floatValue()

Is this correct and why was it changed? Or is this only related to the BioFormats package itself?

Cheers,

Sebastian

**Comment by joshmoore** [comment]
From http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-May/005349.html : 
 > you are correct. This API was modified between 5.0.x and 5.1.x as part of the
changes to support units in the model.

**Comment by sebi06** [comment]
OK. Thanks. So I will adapt my code.

Sebi
