### ISSUE TITLE
python_bioformats works from inside PyCharm but does note from IPython notebook

### ISSUE THREAD

**Issue by sebi06** [CellProfiler/python-bioformats#27]
Hi guys,

i use python-biofromats to read the metadata from our CZI files. When I try this inside PyCharm it works fine
![pycharm_output](https://cloud.githubusercontent.com/assets/3833249/8596858/10699f6e-2652-11e5-9152-d1c7643869ce.png)

When I try this from an IPython notebook and run the exact same lines of code, I get the following errors:

Using bioformats_package : bioformats_package.jar
Failed to get class loci/common/RandomAccessInputStream

JavaException                             Traceback (most recent call last)
<ipython-input-7-22d39db4b763> in <module>()
      1 # get image meta-information
----> 2 MetaInfo = bf.bftools.get_relevant_metainfo_wrapper(CZIfilename)

c:\Users\M1SRH\Documents\Spyder_Projects\BioFormatsRead\bfimage\bftools.pyc in get_relevant_metainfo_wrapper(filename)
    460 
    461     # get JavaMetaDataStore and SeriesCount
--> 462     jmd, MetaInfo['TotalSeries'], IMAGEID = get_java_metadata_store(filename)
    463 
    464     # get dimension information and MetaInfo

c:\Users\M1SRH\Documents\Spyder_Projects\BioFormatsRead\bfimage\bftools.pyc in get_java_metadata_store(imagefile)
    100         jvm_error()
    101 
--> 102     rdr = bioformats.get_image_reader(None, path=imagefile)
    103 
    104     # for "whatever" reason the number of total series can only be accessed here ...

C:\Python27\lib\site-packages\bioformats\formatreader.pyc in get_image_reader(key, path, url)
    904         old_count, rdr = __image_reader_cache[path, url]
    905     else:
--> 906         rdr = ImageReader(path=path, url=url)
    907         old_count = 0
    908     __image_reader_cache[path, url] = (old_count+1, rdr)

C:\Python27\lib\site-packages\bioformats\formatreader.pyc in __init__(self, path, url, perform_init)
    620         self.stream = jutil.make_instance('loci/common/RandomAccessInputStream',
    621                                           '(Ljava/lang/String;)V',
--> 622                                           self.path)
    623 
    624         self.rdr = None

C:\Python27\lib\site-packages\javabridge\jutil.pyc in make_instance(class_name, sig, *args)
   1681     jexception = get_env().exception_occurred()
   1682     if jexception is not None:
-> 1683         raise JavaException(jexception)
   1684     method_id = get_env().get_method_id(klass, '<init>', sig)
   1685     jexception = get_env().exception_occurred()

JavaException: loci/common/RandomAccessInputStream

This feels strange. Can it be that the iypthon notebook does not know where to look for the bioformats_package? The bioformats_package.jar is in the same folder as the bfimage package. See attachment.

![pycharm_bioformats_package_location](https://cloud.githubusercontent.com/assets/3833249/8597001/ff52eb6c-2652-11e5-88da-33a4efb5a4a7.png)

Any ideas what the problem might be?

**Comment by LeeKamentsky** [comment]
What is the line you use to start the Javabridge? My first guess is that you're not using an absolute path to bioformats_package.jar.

**Comment by sebi06** [comment]
Thsi woks now.
