### ISSUE TITLE
javabridge problem -  loci/common/RandomAccessInputStream

### ISSUE THREAD

**Issue by sebi06** [CellProfiler/python-bioformats#29]
Hi Guys,

When I dowbload python-bioformats via pip and run my usual test script, I always get:

C:\Python27\python.exe C:/Users/M1SRH/Documents/Spyder_Projects/BioFormatsRead/test_get_image6d.py
Failed to get class loci/common/RandomAccessInputStream
java.lang.NoClassDefFoundError: loci/common/RandomAccessInputStream
Caused by: java.lang.ClassNotFoundException: loci.common.RandomAccessInputStream
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
Traceback (most recent call last):
  File "C:/Users/M1SRH/Documents/Spyder_Projects/BioFormatsRead/test_get_image6d.py", line 16, in <module>
    MetaInfo = bf.bftools.get_relevant_metainfo_wrapper(filename)
  File "C:\Users\M1SRH\Documents\Spyder_Projects\BioFormatsRead\bfimage\bftools.py", line 474, in get_relevant_metainfo_wrapper
    jmd, MetaInfo['TotalSeries'], IMAGEID = get_java_metadata_store(filename)
  File "C:\Users\M1SRH\Documents\Spyder_Projects\BioFormatsRead\bfimage\bftools.py", line 105, in get_java_metadata_store
    rdr = bioformats.get_image_reader(None, path=imagefile)
  File "C:\Python27\lib\site-packages\bioformats\formatreader.py", line 906, in get_image_reader
    rdr = ImageReader(path=path, url=url)
  File "C:\Python27\lib\site-packages\bioformats\formatreader.py", line 622, in __init__
    self.path)
  File "C:\Python27\lib\site-packages\javabridge\jutil.py", line 1683, in make_instance
    raise JavaException(jexception)
javabridge.jutil.JavaException: loci/common/RandomAccessInputStream

But when I run the same script but add the newest bioformats_package.jar to the path it works (see below). Any idea what the problem might be here? I am using Win7 64bit and Java 8 Update 60 (Build 1.8.0_60-b27)

....
jars = jv.JARS + [BFPATH]
 #jars = jv.JARS
jv.start_vm(class_path=jars, max_heap_size=max_heap_size)
VM_STARTED = True

And the next strange effect occurs when I try to use python-bioformats from inside a little Qt application.

- start Qt application with newest bioformats_package.jar--> same error as mentioned above
- start usual test script with bioformats_package.jar --> works OK
- start Qt application again --> now it works ???

Any idea, why it does not work in the first place?

Sebi

**Comment by LeeKamentsky** [comment]
It does sound like somehow the old BioFormats is being preferentially loaded. We do honor the CLASSPATH environment variable. Could you check to see if CLASSPATH is defined and if so, run again without it defined?

Thx,
--Lee

**Comment by sebi06** [comment]
Hi Lee,

among my environmental variables (I used "set" in cmd)  there is no CLASSPATH.

Sebi

**Comment by sebi06** [comment]
Hi Lee,

I tried some more tests. I am not sure, if that made sense, but I just do not ubdserstand, why it works from inside a python script, but not from inside an application using PyQt for the GUI...

And why do I always have to specify and "extra" path. Shouldn´t python-bioformats works by itself, since it contains the loci_tools.jar?


Test1

import os
import javabridge as jv
import bioformats

#path = r'C:\Users\M1SRH\Documents\Software\BioFormats_Package\5.1.4\bioformats_package.jar'
#path = r'c:\Python27\Lib\site-packages\bioformats\jars\loci_tools.jar'
jars = jv.JARS# + [path]
jv.start_vm(class_path=jars, max_heap_size='2G')
paths = jv.JClassWrapper('java.lang.System').getProperty('java.class.path').split(";")

for path in paths:
    print "%s: %s" %("exists" if os.path.isfile(path) else "missing", path)

filename = r'c:\Users\M1SRH\Documents\Z-Stack.czi'
rdr = bioformats.get_image_reader(None, path=filename)

Output1:

C:\Python27\python.exe C:/Users/M1SRH/Documents/Spyder_Projects/PSFBead_Fit/test_classpath.py
exists: C:\Python27\lib\site-packages\javabridge\jars\rhino-1.7R4.jar
exists: C:\Python27\lib\site-packages\javabridge\jars\runnablequeue.jar
exists: C:\Python27\lib\site-packages\javabridge\jars\cpython.jar
Failed to get class loci/common/RandomAccessInputStream
java.lang.NoClassDefFoundError: loci/common/RandomAccessInputStream
Caused by: java.lang.ClassNotFoundException: loci.common.RandomAccessInputStream
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
Traceback (most recent call last):
  File "C:/Users/M1SRH/Documents/Spyder_Projects/PSFBead_Fit/test_classpath.py", line 15, in <module>
    rdr = bioformats.get_image_reader(None, path=filename)
  File "C:\Python27\lib\site-packages\bioformats\formatreader.py", line 906, in get_image_reader
    rdr = ImageReader(path=path, url=url)
  File "C:\Python27\lib\site-packages\bioformats\formatreader.py", line 622, in __init__
    self.path)
  File "C:\Python27\lib\site-packages\javabridge\jutil.py", line 1683, in make_instance
    raise JavaException(jexception)
javabridge.jutil.JavaException: loci/common/RandomAccessInputStream


Test2

import os
import javabridge as jv
import bioformats

path = r'C:\Users\M1SRH\Documents\Software\BioFormats_Package\5.1.4\bioformats_package.jar'
#path = r'c:\Python27\Lib\site-packages\bioformats\jars\loci_tools.jar'
jars = jv.JARS + [path]
jv.start_vm(class_path=jars, max_heap_size='2G')
paths = jv.JClassWrapper('java.lang.System').getProperty('java.class.path').split(";")

for path in paths:
    print "%s: %s" %("exists" if os.path.isfile(path) else "missing", path)

filename = r'c:\Users\M1SRH\Documents\Z-Stack.czi'
rdr = bioformats.get_image_reader(None, path=filename)

Output2:

C:\Python27\python.exe C:/Users/M1SRH/Documents/Spyder_Projects/PSFBead_Fit/test_classpath.py
exists: C:\Python27\lib\site-packages\javabridge\jars\rhino-1.7R4.jar
exists: C:\Python27\lib\site-packages\javabridge\jars\runnablequeue.jar
exists: C:\Python27\lib\site-packages\javabridge\jars\cpython.jar
exists: C:\Users\M1SRH\Documents\Software\BioFormats_Package\5.1.4\bioformats_package.jar
10:50:44.849 [Thread-0] DEBUG loci.common.NIOByteBufferProvider - Using mapped byte buffer? false
10:50:45.575 [Thread-0] DEBUG loci.common.services.ServiceFactory - Loaded properties from: services.properties
10:50:45.576 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface loci.formats.services.POIService and implementation class loci.formats.services.POIServiceImpl
10:50:45.576 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface loci.formats.services.MDBService and implementation class loci.formats.services.MDBServiceImpl
10:50:45.576 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface loci.formats.services.JPEGTurboService and implementation class loci.formats.services.JPEGTurboServiceImpl
10:50:45.577 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface loci.formats.services.JAIIIOService and implementation class loci.formats.services.JAIIIOServiceImpl
10:50:45.577 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface loci.formats.services.WlzService and implementation class loci.formats.services.WlzServiceImpl
10:50:45.578 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface loci.formats.services.JHDFService and implementation class loci.formats.services.JHDFServiceImpl
10:50:45.579 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface loci.formats.services.NetCDFService and implementation class loci.formats.services.NetCDFServiceImpl
10:50:45.579 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface loci.formats.services.EXIFService and implementation class loci.formats.services.EXIFServiceImpl
10:50:45.579 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface loci.formats.services.MetakitService and implementation class loci.formats.services.MetakitServiceImpl
10:50:45.580 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface loci.formats.services.LuraWaveService and implementation class loci.formats.services.LuraWaveServiceImpl
10:50:45.581 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface loci.formats.services.OMEXMLService and implementation class loci.formats.services.OMEXMLServiceImpl
10:50:45.616 [Thread-0] DEBUG loci.formats.FormatHandler - ZeissCZIReader initializing c:\Users\M1SRH\Documents\Z-Stack.czi
10:50:45.616 [Thread-0] DEBUG loci.formats.FormatHandler - loci.formats.in.ZeissCZIReader.initFile(c:\Users\M1SRH\Documents\Z-Stack.czi)
10:50:46.248 [Thread-0] DEBUG ome.xml.model.ManufacturerSpec - Unable to handle reference of type: class ome.xml.model.EmissionFilterRef
10:50:46.248 [Thread-0] DEBUG ome.xml.model.ManufacturerSpec - Unable to handle reference of type: class ome.xml.model.EmissionFilterRef
10:50:46.248 [Thread-0] DEBUG ome.xml.model.ManufacturerSpec - Unable to handle reference of type: class ome.xml.model.EmissionFilterRef
10:50:46.248 [Thread-0] DEBUG ome.xml.model.ManufacturerSpec - Unable to handle reference of type: class ome.xml.model.EmissionFilterRef


Test3

import os
import javabridge as jv
import bioformats

#path = r'C:\Users\M1SRH\Documents\Software\BioFormats_Package\5.1.4\bioformats_package.jar'
path = r'c:\Python27\Lib\site-packages\bioformats\jars\loci_tools.jar'
jars = jv.JARS + [path]
jv.start_vm(class_path=jars, max_heap_size='2G')
paths = jv.JClassWrapper('java.lang.System').getProperty('java.class.path').split(";")

for path in paths:
    print "%s: %s" %("exists" if os.path.isfile(path) else "missing", path)

filename = r'c:\Users\M1SRH\Documents\Z-Stack.czi'
rdr = bioformats.get_image_reader(None, path=filename)

Output3

C:\Python27\python.exe C:/Users/M1SRH/Documents/Spyder_Projects/PSFBead_Fit/test_classpath.py
exists: C:\Python27\lib\site-packages\javabridge\jars\rhino-1.7R4.jar
exists: C:\Python27\lib\site-packages\javabridge\jars\runnablequeue.jar
exists: C:\Python27\lib\site-packages\javabridge\jars\cpython.jar
exists: c:\Python27\Lib\site-packages\bioformats\jars\loci_tools.jar
log4j:WARN No appenders could be found for logger (loci.common.NIOByteBufferProvider).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**Comment by LeeKamentsky** [comment]
Bio-formats can't start the Javabridge with its jars because you might need to specify other jars as input to javabridge and you probably don't want bioformats to be in charge of shutting down javabridge (I've never been able to figure out a good way to automatically kill the VM as Python tries to exit).

Regarding QT, I was just thinking about your problem and it may have to do with threads. Javabridge initializes the thread that you use to start it, but for any other thread, you need a javabridge.attach() as the thread starts and javabridge.detach() before the thread exits. This prepares the JVM's stack for that thread. It's also safe to do javabridge.attach() / javabridge.detach() within a function that uses the Javabridge - just make sure it's exception-safe.

**Comment by sebi06** [comment]
Hi Lee,

I cleanup my whole System and installed all libraries from the scratch. And now the Problem is gone, ist works as ecpected, even launcheing it from the QT app.
I will check if your tip with the attach / detach helps.

Sebi
