### ISSUE TITLE
Updating docstring for `write_image`

### ISSUE THREAD

**Issue by jakirkham** [CellProfiler/python-bioformats#30]
Looks like ( https://github.com/CellProfiler/python-bioformats/blob/master/bioformats/formatwriter.py#L62-L66 ) params should have underscore and lower case letter instead ( https://github.com/CellProfiler/python-bioformats/blob/master/bioformats/formatwriter.py#L46 ).

**Comment by LeeKamentsky** [comment]
good eye - btw feel free to submit a pull request for that, it might even get it fixed faster.

**Comment by jakirkham** [comment]
Probably will. Just wanted to make a quick note instead of getting sidetracked right now.

**Comment by jakirkham** [comment]
Add the PR ( https://github.com/CellProfiler/python-bioformats/pull/33 ).
