### ISSUE TITLE
Version info no longer works

### ISSUE THREAD

**Issue by jakirkham** [CellProfiler/python-bioformats#32]
It appears version information used to be in another file ( https://github.com/CellProfiler/python-bioformats/blob/master/bioformats/__init__.py#L13 ). However, that file does not appear to exist. Also, it looks like `python-javabridge` has the same issue.

**Comment by LeeKamentsky** [comment]
Those are made by [setup.py](https://github.com/CellProfiler/python-bioformats/blob/master/setup.py#L23). In order to get them, you should follow the directions here:
http://pythonhosted.org/javabridge/developers.html . I think

    python setup.py develop

will set things up for you.

**Comment by jakirkham** [comment]
So, I installed both using `python setup.py install`. However, version information only appears to work for `python-javabridge`, but not `python-bioformats`. Is there a reason that would happen?

**Comment by LeeKamentsky** [comment]
The setup script does run `git describe` on the root directory in order to get the version:

    $ git describe
    1.0.5

If yours doesn't do that, maybe that could cause the problem. I can't think of much else. The script:

    import bioformats
    bioformats.__version__

prints 1.0.5 for me. I do have a copy of _version.py in my bioformats directory:

    >>>> import os
    >>>> print "\n".join(os.listdir(os.path.dirname(bioformats.__file__)))

    formatreader.py
    formatreader.pyc
    formatwriter.py
    formatwriter.pyc
    jars
    log4j.py
    log4j.pyc
    metadatatools.py
    metadatatools.pyc
    noseplugin.py
    omexml.py
    omexml.pyc
    tests
    _version.py
    _version.pyc
    __init__.py
    __init__.pyc

**Comment by jakirkham** [comment]
I can no longer reproduce this issue. Closing...

**Comment by jakirkham** [comment]
Also, not sure if you have heard of this project ( https://github.com/warner/python-versioneer ). It basically does what you are doing now, but all follows [PEP440]( https://www.python.org/dev/peps/pep-0440 ). As it is licensed as Public Domain it shouldn't harm you in terms of trying to stay as close to BSD, as possible. It also is installed within your codebase so is not a separate dependency per se.

**Comment by LeeKamentsky** [comment]
Thx - will take a look at it.
