### ISSUE TITLE
log4j output

### ISSUE THREAD

**Issue by polarise** [CellProfiler/python-bioformats#45]
Hi,

Thank you very much for a very handy wrapper.

I've been seeing the following output every time I run a Python script that uses `python-bioformats`:

```
log4j:WARN No appenders could be found for logger (loci.common.NIOByteBufferProvider).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

To the best of my ability, I've not been able to find out from the documentation how to handle this. The only way I could silence it was by poking around the code where I found the function `init_logger()` in the `__init__.py` file. Placing this after the `javabridge.start_vm(...)` call silenced this though I don't know where the log files (if any) vanish to.

Please document this so that it can be better handled.

Thanks.

@polarise

**Comment by mcquin** [comment]
Hi @polarise 

You need to configure a logger and add it to the class path. You can [follow this example](https://github.com/CellProfiler/python-bioformats/blob/39f2aa8360324b4129284d4f647d4f7ee7797518/tests/conftest.py#L11-L21) (although, the `assert` is unnecessary).
