### ISSUE TITLE
Unable to install using pip

### ISSUE THREAD

**Issue by rchurt** [CellProfiler/python-bioformats#56]
Hello,
When I try to install python-bioformats using pip, it fails with the follow error:

```

pip install python_bioformats
Collecting python-bioformats
  Using cached python-bioformats-1.0.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jn/pt_9j7j52wz9jq8bzlg7bf1h0000gn/T/pip-build-6pz2zxe9/python-bioformats/setup.py", line 47, in <module>
        version=get_version().decode("utf-8"),
    AttributeError: 'str' object has no attribute 'decode'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/jn/pt_9j7j52wz9jq8bzlg7bf1h0000gn/T/pip-build-6pz2zxe9/python-bioformats/
```

Any suggestions?

Thanks,
Rob

**Comment by michaelosthege** [comment]
I also have this issue..

**Comment by yalexand** [comment]
I too get the same error. 
I try to use python bioformats to read ome.tiffs

The command `pip install bioformats` installs

> cached bioformats-0.1.14-py2.py3-non-any.whl

which doesn't contain advertised stuff.

**Comment by darosio** [comment]
I have the same AttributeError because in python3 'str' does not have the 'decode' attribute.
It should be easy to fix in the setup.py file.

To  yalexand: please mind that you should use:
pip install python-bioformats

**Comment by mcquin** [comment]
This appears to have been resolved.
