### ISSUE TITLE
Documentation on building from source

### ISSUE THREAD

**Issue by jni** [CellProfiler/python-bioformats#59]
I'm having the same issue as #56, so I tried installing from source with `pip install .`, and got the following error message:

```
    _javabridge.c:244:10: fatal error: 'jni.h' file not found
    #include "jni.h"
             ^
    1 warning and 1 error generated.
    error: command 'gcc' failed with exit status 1
```

I do have Eclipse JDK but don't know how to point the install to it... Any hints?

**Comment by mcquin** [comment]
I believe this is resolved. The package can be installed with `pip`.
