### ISSUE TITLE
ImportError javabridge although Cellprofiler installed fine

### ISSUE THREAD

**Issue by anou85** [CellProfiler/python-bioformats#77]
Hi, 

I'm using Ubuntu 16.04 and installed the requirements listed on [https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-(Ubuntu-16.04-LTS)]
Everything installed fine, but when I'm trying to execute Cellprofiler with 

$ cellprofiler I get this error:

Traceback (most recent call last):
  File "/home/anja/.local/bin/cellprofiler", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'CellProfiler' distribution was not found and is required by the application

and with $ python Cellprofiler.py this error:

Traceback (most recent call last):
  File "CellProfiler.py", line 4, in <module>
    cellprofiler.__main__.main()
  File "/home/anja/CellProfiler/cellprofiler/__main__.py", line 175, in main
    from cellprofiler.utilities.cpjvm import cp_start_vm
  File "/home/anja/CellProfiler/cellprofiler/utilities/cpjvm.py", line 3, in <module>
    import javabridge
ImportError: No module named javabridge

re-checking python-bioformats gave:

Requirement already satisfied: python-bioformats in /home/anja/.local/lib/python2.7/site-packages
Requirement already satisfied: javabridge>=1.0 in /home/anja/.local/lib/python2.7/site-packages (from python-bioformats)
Requirement already satisfied: numpy in /usr/lib/python2.7/dist-packages (from javabridge>=1.0->python-bioformats)

Is it anything obvious I'm missing?

Thanks for your help

**Comment by LeeKamentsky** [comment]
Hi Anou85, your best bet is to go through the CellProfiler development team (e.g. file an issue at the CellProfiler/CellProfiler repo or ask on your forum). I think the first step might be to issue the command, `pip freeze` and post the output. That could tell us what's installed.

**Comment by anou85** [comment]
Hi, thank you for your reply. This is what `pip freeze` gave:
adium-theme-ubuntu==0.3.4
beautifulsoup4==4.4.1
chardet==2.3.0
cycler==0.9.0
Cython==0.23.4
decorator==4.0.6
gnome-gmail==2.0.1
h5py==2.6.0
html5lib==0.999
lxml==3.5.0
matplotlib==1.5.1
mysqlclient==1.3.7
numpy==1.11.0
Pillow==3.1.2
pygobject==3.20.0
pygpgme==0.3
pyparsing==2.0.3
python-dateutil==2.4.2
pytz==2014.10
pyzmq==15.2.0
scipy==0.17.0
scour==0.32
six==1.10.0
unity-lens-photos==1.0
wxPython==3.0.2.0
wxPython-common==3.0.2.0

Does that help?

**Comment by anou85** [comment]
Okay, I seemed to have managed to install it. I had the wrong bioformats module (not the python-bioformats one). 
Now it's just throwing an error about the ilastik_main module, but it seems that this is work in progress (<https://github.com/CellProfiler/CellProfiler/issues/2393>)?
Thanks for the pip freeze tip, it helped me identify the missing packages :)

**Comment by LeeKamentsky** [comment]
Good job - closing this now.

**Comment by isfj** [comment]
I got the same error as you! How do you fix it finally?
