### ISSUE TITLE
Bio-formats 5.5

### ISSUE THREAD

**Issue by nerduno** [CellProfiler/python-bioformats#82]
When will python-bioformats be upgraded to wrap bio-formats version 5.5?  Version 5.5 supports Olympus's new file format (.oir).  It would be great to be able to load these files from python.

**Comment by mcquin** [comment]
@nerduno I'm looking upgrading bioformats today. :)

**Comment by mcquin** [comment]
Related: https://github.com/CellProfiler/prokaryote/issues/27

**Comment by mcquin** [comment]
Resolved #83
