### ISSUE TITLE
`bioformats.__version__` should print package version

### ISSUE THREAD

**Issue by mcquin** [CellProfiler/python-bioformats#86]
From @oleksandr-pavlyk:

> With current source for python-bioformats, `import bioformats; bioformats.__version__` returns `u’0.0.0’`, due to missing `_version.py` in the github repo, or due to setup.py not creating it.  There is also a problem with importing `_version.py` in `bioformats/__init__.py`. It should use relative path, like `from  ._version import __version__`, rather than absolute path (`from  _version import __version__`). This is probably an oversight, as the _version file is expressly added to the `.gitignore` file.

**Comment by ehrenfeu** [comment]
The functionality for generating the package version string based on git tags was added in e2e5e93a7c160ec46847dfecc987ce30ccb2be11, this is also where the entry in `.gitignore` comes from:

https://github.com/CellProfiler/python-bioformats/blob/e2e5e93a7c160ec46847dfecc987ce30ccb2be11/.gitignore#L6

For some reason (not mentioned in the commit message), this code was removed again in b4129354c143419db07a06c45e1d08bc608e129a, unfortunately without putting anything functionally equivalent there, and without removing the corresponding line from `.gitignore`. Therefore, the package itself will have a correct version number (hardcoded in `setup.py`), but it won't be available through `bioformats.__version__`.

In addition to what is described above, not only the version available in the Python code should be auto-generated, but also the Sphinx-generated documentation should get this information without having to edit additional files.

Digging deeper into a simple solution for this, I came across the official instructions for [single-sourcing the package version](https://packaging.python.org/guides/single-sourcing-package-version/) on the Python Packaging User Guide, recommending the use of [setuptools_scm](https://pypi.org/project/setuptools_scm/). I'll test on a topic branch and create a PR once I'm happy with the results.
