### ISSUE TITLE
PyPI Issue: Only able to import methods from bioformats when installing from github using setup-tools

### ISSUE THREAD

**Issue by mjlbach** [CellProfiler/python-bioformats#92]
Apologies if this has been answered somewhere else or if my terminology is incorrect. I can't seem to access any of the methods of bioformats when installing python-bioformats using pip; only if I build the library myself from github. I'm using python 3.6.3 in a conda virtual environment; I've tried using the pip and conda builds of python-bioformats and python-javabridge to no avail. The only way it works is if I clone and build python-bioformats from this repo.

**Comment by mcquin** [comment]
Hi @mjlbach,

Thanks for reporting this issue. Could you please tell me which versions of python-bioformats and javabridge you installed via pip?

Is it correct that you can run python-bioformats from source with pip installed javabridge?

Thanks,
Claire

**Comment by mjlbach** [comment]
Hi @mcquin,

I just checked and for some reason my conda environment was installing from a wheel of 1.1.0. This is fixed in 1.3.5. Sorry about that!

Best,
Michael

**Comment by mcquin** [comment]
No problem! No fixes are the best fixes. :)
